default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: y_app
  password: 12344478Aa
  host: localhost

development:
  <<: *default
  database: y_app_development
